export const wrapper: string;
export const itemWrapper: string;
export const left: string;
export const right: string;
export const top: string;
export const username: string;
export const time: string;
export const reply: string;
export const bottom: string;
